/** Declaration file generated by dts-gen */

declare function ppo(): void;

declare namespace ppo {
    const prototype: {
    };

    interface Trash {  
        clear: () => void;  
        log: () => void;  
        [key: string]: any; 
    }
    
    var trash: Trash;  

    function args(e?: any, t?: number): any;

    function clearTimesout(e?: any): void;

    function delLastComma(t?: string): string;

    function deleteLastComma(t?: string): string;

    function construct(...args: any[]): any;

    function currency(e?: any): any;

    function delCookie(e: any): void;

    function delUrlParam(e: any, t?: any): any;

    function deleteCookie(e: string): void;

    function deleteUrlParam(e: any, t?: string): string;

    function fill0(e?: number): number;

    function floor(e?: number, t?: number): number;

    function getCookie(e?: any): null | string;

    function getDate(e?: string, t?: string): string;

    function getUrlParam(e?: string, t?: string): string;

    function hash(e?: string): any;

    function ieVer(): any;

    function ieVersion(): number;

    function isAndroid(): boolean;

    function isIE(): boolean;

    function isIOS(): boolean;

    function isIPad(): boolean;

    function isIos(): boolean;

    function isMobile(): boolean;

    function isPC(): boolean;

    function isTypeof(e?: any, t?: string): boolean;

    function isWeixin(): boolean;

    function judge(e: any, t?: any, o?: boolean | string): boolean;

    function judgment(e: any, t?: any, o?: any): any;

    function loadjs(e: string, t?: any, o?: any): void;

    function lockTouch(): void;

    function log(e?: string, t?: any): void;

    function logs(...args: any[]): void;

    function noop(): void;

    function open(e?: string): void;

    function paramsName(e?: any): any;

    function randomA2B(e?: any, t?: any, o?: any): any;

    function randomColor(): string;

    function randomFromA2B(e?: number, t?: number, o?: number): number;

    function randomFromArray(e?: any[]): any;

    function randomKey(e?: number): string;

    function randomfArr(e?: any): any;

    function removeConsole(e?: string|boolean): void;

    function setCookie(e: string, t?: any, o?: any): void;

    function setTimesout(...args: any[]): any;

    function setUrlParam(e: any, t?: any, o?: string): string;

    function toJSON(res: any): any;

    function toArray(obj, dot): any;

    function toJson(res: any): any;

    function tojson(res: any): any;

    function trigger(e: any, t?: any, o?: string): any;

    function ua(e?: any): string;

    function uuid(): string;
}

export default ppo;