/** Declaration file generated by dts-gen */

declare function ppo(): void;

declare namespace ppo {
    const prototype: {
    };

    function args(e?: any, t?: any): any;

    function clearTimesout(e?: any): void;

    function construct(...args: any[]): any;

    function currency(e?: any): any;

    function delCookie(e: any): void;

    function delUrlParam(e: any, t?: any): any;

    function deleteCookie(e: any): void;

    function deleteUrlParam(e: any, t?: any): any;

    function fill0(e?: any): any;

    function floor(e?: any, t?: any): any;

    function getCookie(e?: any): any;

    function getDate(e?: any, t?: any): any;

    function getUrlParam(e?: any, t?: any): any;

    function hash(e?: any): any;

    function ieVer(): any;

    function ieVersion(): any;

    function isAndroid(): any;

    function isIE(): any;

    function isIOS(): any;

    function isIPad(): any;

    function isIos(): any;

    function isMobile(): any;

    function isPC(): any;

    function isTypeof(e?: any, t?: any): any;

    function isWeixin(): any;

    function judge(e: any, t?: any, o?: any): any;

    function judgment(e: any, t?: any, o?: any): any;

    function loadjs(e: any, t?: any, o?: any): void;

    function lockTouch(): any;

    function log(e?: any, t?: any): void;

    function logs(...args: any[]): void;

    function noop(): void;

    function open(e?: any): void;

    function paramsName(e?: any): any;

    function randomA2B(e?: any, t?: any, o?: any): any;

    function randomColor(): any;

    function randomFromA2B(e?: any, t?: any, o?: any): any;

    function randomFromArray(e?: any): any;

    function randomKey(e?: any): any;

    function randomfArr(e?: any): any;

    function removeConsole(e?: any): void;

    function setCookie(e: any, t?: any, o?: any): void;

    function setTimesout(...args: any[]): any;

    function setUrlParam(e: any, t?: any, o?: any): any;

    function toJSON(res: any): any;

    function toJson(res: any): any;

    function tojson(res: any): any;

    function trigger(e: any, t?: any, o?: any): any;

    function ua(e?: any): any;

    function uuid(): any;
}

export default ppo;